# Game Theory Agents

In [1]:
import numpy as np
from game_simulation import simulate_match_up
from agent import *
from game import get_default_game, Game, get_snowdrift_game

## Define an own Agent

In [2]:
class MyAgent(Agent):
    
    """ Define your own Agent """
    def __init__(self, player_id, game):
        super().__init__(player_id, game)

    def get_action(self, last_action_p1, last_action_p2) -> Action:
        if not last_action_p1:
            return Action.Cooperate
        # start with cooperate
        if self.player_id == 1:
            if (last_action_p2 == Action.Cooperate):
                return Action.Cooperate
            # wenn gegner in der letzten runde  cooperate -> cooperate
            else:
                return Action.Defect
            # wenn gegner in der letzten runde defect -> defect
        else:
            if (last_action_p1==Action.Cooperate):
                return Action.Cooperate
            else:
                return Action.Defect
            

## Test my agent against a specific bot.




In [3]:
GAMES_PER_MATCHUP = 100
game = get_default_game()  # or define your own using Game()  (see game.py for details)
print(game, "\n")

# evaluate a specific match-up, e.g. MyAgent vs. CopycatAgent  (index 1 vs index 2)
agents=[MyAgent, GrudgerAgent]
print(f"{agents[0](1,game)} vs. {agents[1](1,game)} -> {simulate_match_up(agents[0], agents[1], game, GAMES_PER_MATCHUP)}")   

Game Payoff matrixes:
player 1 payoff: 
           Cooperate  Defect
Cooperate          2      -1
Defect             3       0

player 2 payoff: 
           Cooperate  Defect
Cooperate          2       3
Defect            -1       0 

MyAgent vs. GrudgerAgent -> (200, 200)


## Simulate a small tournament

Play out all combinations of agents. The following agents are available:
- AllCooperateAgent
- AllDefectAgent
- CopycatAgent
- RandomAgent
- GrudgerAgent
- DetectiveAgent

Add your agent to the list in the first line to test it against all other agents.

In [8]:
agents = [MyAgent, AllCooperateAgent, AllDefectAgent, CopycatAgent, RandomAgent, GrudgerAgent, DetectiveAgent]
results = np.zeros((2, len(agents), len(agents)))
for id1, player1 in enumerate(agents):
    for id2, player2 in enumerate(agents):
        results[:, id1, id2] = simulate_match_up(player1, player2, game, GAMES_PER_MATCHUP)
print(results, "\n")
# results[:, agent1, agent2] contains the results of simulate_match_up(agent1, agent2, game)

for id, agent in enumerate(agents):
    print(f"total points of agent: {agent(1,game)} = {sum(results[0,id,:]) + sum(results[1,:,id])}")

[[[ 200.  200.  -99.  200.  116.  200.  149.]
  [ 200.  200.    0.  200.  102.  200.    4.]
  [ -96.  300. -100.  -96.  116.  -96.  -92.]
  [ 200.  200.  -99.  200.   83.  200.  149.]
  [ 114.  251.  -45.  106.  128.  -54.  103.]
  [ 200.  200.  -99.  200.  100.  200.  -92.]
  [ 152.  298.  -98.  152.   95.  -92.  197.]]

 [[ 200.  200.  -96.  200.  119.  200.  152.]
  [ 200.  200.  300.  200.  249.  200.  298.]
  [ -99.    0. -100.  -99.  -46.  -99.  -98.]
  [ 200.  200.  -96.  200.   86.  200.  152.]
  [ 111.   98.  120.  103.  101.   69.  100.]
  [ 200.  200.  -96.  200.  -44.  200.  -92.]
  [ 149.    4.  -92.  149.   95.  -92.  197.]]] 

total points of agent: MyAgent = 1927.0
total points of agent: AllCooperateAgent = 1808.0
total points of agent: AllDefectAgent = -124.0
total points of agent: CopycatAgent = 1886.0
total points of agent: RandomAgent = 1163.0
total points of agent: GrudgerAgent = 1387.0
total points of agent: DetectiveAgent = 1413.0


## SnowDrift

In [5]:
game = get_snowdrift_game()
agents = [MyAgent, AllCooperateAgent, AllDefectAgent, CopycatAgent, RandomAgent, GrudgerAgent, DetectiveAgent]
results = np.zeros((2, len(agents), len(agents)))
for id1, player1 in enumerate(agents):
    for id2, player2 in enumerate(agents):
        results[:, id1, id2] = simulate_match_up(player1, player2, game, GAMES_PER_MATCHUP)
print(results, "\n")
# results[:, agent1, agent2] contains the results of simulate_match_up(agent1, agent2, game)

for id, agent in enumerate(agents):
    print(f"total points of agent: {agent(1,game)} = {sum(results[0,id,:]) + sum(results[1,:,id])}")

[[[ 200.  200.  -99.  200.   98.  200.  149.]
  [ 200.  200.    0.  200.   88.  200.    4.]
  [ -96.  300. -100.  -96.   84.  -96.  -92.]
  [ 200.  200.  -99.  200.  117.  200.  149.]
  [  72.  260.  -50.  123.  102.  -46.   92.]
  [ 200.  200.  -99.  200.   88.  200.  -92.]
  [ 152.  298.  -98.  152.  115.  -92.  197.]]

 [[ 200.  200.  -96.  200.  101.  200.  152.]
  [ 200.  200.  300.  200.  256.  200.  298.]
  [ -99.    0. -100.  -99.  -54.  -99.  -98.]
  [ 200.  200.  -96.  200.  120.  200.  152.]
  [  69.   80.  100.  120.  126.   83.   92.]
  [ 200.  200.  -96.  200.  -47.  200.  -92.]
  [ 149.    4.  -92.  149.  115.  -92.  197.]]] 

total points of agent: MyAgent = 1867.0
total points of agent: AllCooperateAgent = 1776.0
total points of agent: AllDefectAgent = -176.0
total points of agent: CopycatAgent = 1937.0
total points of agent: RandomAgent = 1170.0
total points of agent: GrudgerAgent = 1389.0
total points of agent: DetectiveAgent = 1425.0
